   /**
     * 乡村医生页面
     */

var contentData = {
        countrydoctor:{
        wwh:{
            wb1:"For 36 years, he has never left his post, sticking to the health station in Tianxingpo Village, Mata Town, using all he has learned to relieve the pain of the local people, leaving the most beautiful youth to the remote and backward countryside.<p>Wang Wuhui was deeply influenced by his uncle who was also a doctor. He loved medicine and studied medicine with his uncle.After Maoming's further study, he went back to the countryside. Doctor's profession is a ragrant baboon wherever it is. Wang Wuhui hesitated to go to the city for employment, but when he saw the poor villagers'difficulty in seeing a doctor, he couldn't bear it, so he stayed in the village.</p> <p>Wang Wuhui is very busy every day, less than 80 square meters of the clinic, from the doctor, dispensing, injection are operated by him alone. With the idea of  doctor s parents heart , he listened patiently to the patient's state of illness. Every patient should be observed and cared for meticulously in the work, and medication should be taken cautiously. Whether it was cold or hot, during the day or at night, he did his duty, often tossing and turning all night without sleeping. Sometimes when a patient comes to the door just after he starts his job at home, he will put down his chopsticks to see the doctor first. Even at the beginning of the new year, he has not asked for leave, let alone the usual weekend.</p>",
            img1:"country_doctor_wwh_left.jpg",
            img2:"country_doctor_wwh_center.jpg",
            wb2:"One day in December 2017, the weather was very cold. There was a villager named Zhang Zilan in Tianxingpo Village. It was two o'clock that night. She suddenly felt stomachache. She wanted to see Dr. Wang Wuhui, but thought th at he had been busy all day and could not disturb his rest. But as time went by, the stomachache became worse and worse, so she picked up the phone and called Dr. Wang. The telephone was swiftly put through. Doctor Wang got to know the situation. He got up immediately, took his medicine box with him, bicycled to Zhang Zilan's house in spite of the cold, and went to see a doctor, dispense medicine, give an injection for her, and told her to pay attention to it. Wang Wuhui did not rest all night, and the next day he still treated the villagers as usual. Wang Wuhui is just like this, conscientious and hardworking for the villagers.<p>In order to serve the people better, Wang Wuhui insists on learning professional knowledge every day, constantly learning new knowledge, accumulating experience from all sides, training new technology, and doing his best to serve the villagers. All along, he has maintained a good medical ethics, rigorous working attitude, constantly improve his medical skills, work hard and complain, to encourage patients with a smile.",
            img3:"country_doctor_wwh_right.jpg",
            wb3:"As a village doctor, Wang Wuhui devoted himself to the rural medical and health services with the greatest enthusiasm. He did not fear the hardship of rural conditions, devoted his efforts silently, dedicated his youth, and guarded the health of Tianxingpo villagers.",
            name:"Wang Wuhui: Leave the most beautiful youth to the countryside",
        },
        sss:{
            wb1:"In 2014, Huang Haiqiu came to Taiping Town Central Hospital of Xichong County to work. At that time, the hospital did not set up a rehabilitation department of traditional Chinese medicine. After receiving the responsibility of establishing the rehabilitation department of traditional Chinese medicine, she began to call people, purchase equipment, renovate the wards, and place the beds. Under her own management, the Department of Traditional Chinese Medicine Rehabilitation of Taiping Central Health Hospital was established from scratch. <br> During the treatment period, Huang Haiqiu treated the patients warmly and thoughtfully. If a patient brings a child to the treatment, in order to disturb others, she either opens the computer to show cartoons to the child, or takes out snacks such as fruits and biscuits; if a patient has a cold in the treatment, she will soon bring boiling water and pills to the front for her to take; if someone has pain in the waist and leg, she will free of charge. They were treated with acupuncture, cupping and scraping. <br> Every day when Huang Haiqiu goes to work, she hardly eats on time at noon and has no rest time. Most of the patients who come to see her are elderly people. Faced with the untidy elderly patients, she will take the initiative to help the elderly to organize and never abandon them.",
            img1:"country_doctor_hhq_left.jpg",
            img2:"country_doctor_hhq_center.jpg",
            wb2:"The old man, Ma Hongshuang, suffered from sudden cerebral hemorrhage due to hypertension. He underwent craniotomy in a large hospital, which resulted in pneumothorax and other symptoms and paralysis in bed. After spending more than 200,000 yuan, the family members of the patients still did not improve, and were forced to leave the hospital due to the limitation of human and financial resources. After that, they found Huang Haiqiu for rehabilitation treatment. <br> In order to make health and health resources more inclined to poor villages and families, Taiping Town Central Hospital has organized many free clinics to send health to villages, in which Huang Haiqiu participated actively. <br> During the free clinic activities, Huang Haiqiu carried medicines, equipment and health propaganda materials to poor villages to provide common and chronic diseases diagnosis and consultation for villagers, and distributed health propaganda materials to villagers to encourage them to develop good habits. <br> She found that the geographical characteristics of the countryside and the long-term rural labor made many villagers suffer from rheumatism, osteoarthritis and other pains. She treated villagers with acupuncture, moxibustion, massage and other treatments for pain and mobility inconvenience on the spot.",
            img3:"country_doctor_hhq_right_.jpg",
            wb3:"There is a kind of beauty, selfless love, far-reaching melodious; there is a kind of love, spring weathering rain, moistening things silently. She is an ordinary rural doctor, adhering to a kind heart, for many years as a day, to help patients relieve their pain, in exchange for the well-being of one side of the people.",
            name:"Wonderful hands, benevolent hearts, Huang Haiqiu",
        },
        zdw:{
            wb1:"In 1992, Zheng Dawei, a village doctor in Zhangzhuang Village, Juling Town, Linying County, opened a village clinic at home. He studied in Xuchang Medical College in 1993 and 1994. During the two years, he learned many skills from his teachers, such as skin diseases, neck, shoulder, waist and leg pain, hypertension, stroke, hemiplegia, sublingual tether removal, etc., especially in the treatment of lumbar snakes. Burns and other aspects are quite effective, and gradually become the clinic's characteristic diagnosis and treatment. <br> Rural grass-roots health work is a hard and glorious task. For more than 20 years, Zheng Dawei has been sticking to the front line of rural grass-roots health work, fearless of severe cold and heat, never complaining, always anxious for patients, thinking of patients, regardless of wind and rain or day and night, as long as patients need to be on call, not afraid of trouble and careful treatment, so that patients can satisfy their families. On the morning of the first year of 2012, an old man in Xuchang suffered from banded herpes. After many inquiries, he knew that he was good at this kind of treatment. His family came with a try mentality. I firmly gave up the chance to have fun with his family and came to the clinic to treat the patients carefully. After several courses of treatment, the patient gradually recovered. I am very grateful that I also sent the Jinqi.",
            img1:"country_doctor_zdw_left.jpg",
            img2:"country_doctor_zdw_center.jpg",
            wb2:"In December 2013, it was more than one o'clock in the middle of the night. A low-income household in Zhangzhuang village suffered from emphysema and heart disease. The situation was very critical. His family called Zheng Dawei for help. Zheng Dawei, regardless of the day's fatigue and cold, immediately got up and ran to the patient's home for rescue. Time is life. Because Zheng Dawei rescued the patient in time, he was able to get out of danger. After more than ten days of observation and nursing, the treatment was improved. Zheng Dawei waived the patient's medical expenses because his family was very difficult. In order to facilitate the masses to seek medical treatment, Zheng Dawei, whether in hot summer, cold winter or snowstorm, visited five insured and poor households in his village all the year round, offered them free treatment, blood pressure, heart rate, blood sugar, patiently explained health knowledge such as hypertension and diabetes, and helped them do rehabilitation exercises, etc. The trust and praise of the masses.",
            img3:"country_doctor_zdw_right.jpg",
            wb3:"Zheng Dawei said: Treating illness and saving people, I think it is the most essential work as a doctor. When people need it most, they come forward to save lives and injuries without asking for repayment.",
            name:"Compare your heart with Zheng Dawei's",
        },
        myh:{
            wb1:"In Luojiahewan Village, Wangtuan Town, Ma Yuhua undertakes the basic medical care of 2464 villagers and 52 basic public health services in 12 categories. This year is her 23rd year in this ordinary and great post. What makes her proudest is not the reputation of the most beautiful village doctor and the excellent country doctor, but the title of National People's Congress representative. <br> In 2013, Ma Yuhua participated in the National People's Congress for the first time. She said: Rural people live widely scattered and rely on village doctors to carry out public health services. The workload is very large, but the income is very low. It is hoped that the treatment of village doctors can be improved from the policy level, so that they can provide better medical services for the vast rural masses more comfortably. <br> In 2014, Ma Yuhua pointed out that village doctors are the bottom of the net of China's medical and health undertakings. If the bottom of the net is broken, the medical undertakings of the whole country will lose important support.",
            img1:"country_doctor_myh_left.jpg",
            img2:"country_doctor_myh_center.jpg",
            wb2:"In 2015, she called for the solution of the problem of the village doctor's old-age care: I am very energetic and able to work, but Yang Jiaolong, a village doctor in Dawan Village, Wangtuan Town, is still busy working every day at the age of 75. Why not retire? Because after retirement, there is no pension insurance for employees and no income source. Among the 249 village doctors in Tongxin County, there are sixty or seventy people over the age of 60. <br> Incorporate rural doctors into the management of township health centers. <br> We should properly solve the problems of old-age security and living difficulties for the elderly rural doctors. <br> Establish a unified and standardized old-age security system for rural doctors to solve the worries of rural doctors. <br> To her satisfaction, all her suggestions were answered. In recent years, the treatment of village doctors in Ningxia has been gradually improved. Village doctors such as Ma Yuhua have received various subsidies in one year, and at least 230,000 yuan of medical education has been collected and sorted out. In order to solve the old-age problem of retired village doctors, our district has also issued policies to enable village doctors to enjoy the basic pension of urban and rural residents, on the basis of which they will also receive the living subsidy of the doctors in the villages away from their posts.",
            img3:"country_doctor_myh_right.jpg",
            wb3:"Money will always be spent, and helping people develop industries is the money tree planted to become rich. Ma Yuhua said.",
            name:"Ma Yuhua: Bring the Heart of the Masses to Beijing",
        },
        xae:{
            wb1:"In 1992, 23-year-old Xie Ai-e came to the remote isolated island of Huxin to become a village doctor with the ambition of saving the world by hanging a pot. She began her 25-year-old medical journey on a boat less than 20 square meters. <br> She could not swim, build a boat, have no electricity on board, and worry about her relatives on the shore and the panic of isolation. Xie Ai-e once wanted to go back to work on the shore, but when she thought of the enthusiastic villagers, her idea disappeared. <br> A small clinic is not only a pharmacy, but also an injection room, an observation room and a diagnostic room. At its peak, it can receive more than 50 patients a day. <br> Over the past 25 years, Xie Aie has been on duty 24 hours without hindrance and insisted on boating. <br> In 2017, Xie Aie was elected as the representative of the Nineteenth National Congress and became the part-time vice president of the Women's Federation of Honghu City. <br> In the field of Huang Haiqiu's treatment, she is good at treating paralysis, cervical spondylosis, lumbar intervertebral disc herniation, sequelae of stroke, hemifacial spasm, gout and other diseases by using traditional Chinese medicine oral administration, acupuncture, massage, acupoint injection, external application of traditional Chinese medicine, cupping and catgut embedding therapy.",
            img1:"country_doctor_xae_left.jpg",
            img2:"country_doctor_xae_center.jpg",
            wb2:"She and her husband have received more than 30,000 patients and made more than 3,000 visits. They have traveled over 80,000 kilometers, which is equivalent to two circles around the equator of the earth. They have transferred more than 100 mothers. Almost all the villagers under the age of 20 are accompanied and cared for by Xie Aie. <br> After 25 years of medical treatment on the lake, Xie Ai-e and the fishermen on the boat had a deep affection like relatives. During the 25 years of on-board medical treatment, Xie Ai-e not only had to treat fishermen, but also shouldered the important task of disseminating public health and medical knowledge. She set up public health files for every fisherman who went on board to see a doctor, so as to facilitate the follow-up of fishermen's condition at any time. Because the fishermen on board come from all over the country, there are difficulties in communication. Some fishermen are illiterate and need to go to the big hospital on shore for examination. Xie Aie accompanies the fishermen to see a doctor in the city. From registration to inspection and hospitalization, she has no complaints before and after her busy schedule. <br> She took the initiative to carry out the propaganda task of one million towel propaganda. With her thoughts and thoughts, she vividly interpreted the spirit of the Nineteenth National Congress to the grass-roots women. With her growing experience, she narrated the changes of Honghu Lake and conveyed full positive energy. For more than a year, her footprints have spread all over Jingchu, Honghu and the fields.",
            img3:"country_doctor_xae_right.jpg",
            wb3:"Xie Aie explained the most beautiful to us with plainness and simplicity. Today, she has never forgotten her original intention, mission, rooted at the grass-roots level, serving the masses, and has never stopped.",
            name:"Xie Ai'e: The medical journey can circle the earth twice.",
        }
    }
}