var contentData = {

    /**
     * 扶贫御风页面
     */
    poverty : {
        /**
         * 秦西宁
         */
        qxn : {
            name : "Qin Xining",
            nr : "<p data-animation=\"fadeInLeft\">The road into the village is still a long mud road, clear and rainy. Six natural villages have not yet hardened their roads to villages, five Miao villages are seriously short of water, and some of the poor people still live a life of inseparability between human beings and livestock. This is Qin Xining's first impression of Gedang Village. On January 13, 2016, Qin Xining, a cadre of the International Cooperation Bureau of the Supreme Peoples Procuratorate, came to Gedang Village, Xinhua Town, Funing County, Yunnan Province, to serve as the first Secretary of poverty alleviation in the village, shouldering the important task of fighting poverty in Gedang Village. That year, when he was 29 years old, his first birthday gift was a hand-painted battle map of the geographical distribution of 13 natural villages in Gedang Village. Qin Xining started from visiting 88 filing and card-making households in 13 villages under the jurisdiction of Gedang Village, and went deep into the villagers homes to have a heart-to-heart talk with them to understand the villagers income and expenditure situation and difficulties at home.</p><p data-animation=\"fadeInLeft\"> The eyes of the masses are bright, calm and quiet. The common people will naturally realize that you are not coming to play soy sauce or come and read. What s more, it s not so-called come and gild. It s doing things for them. Qin Xining said. Only through household survey, can not fully understand the difficulties of families. Qin Xining believes that the situation should be understood in many ways. As a result, he changed his work strategy and took lessons from village cadres as soon as he had time, and talked to the villagers more about his family life, so as to carry out the precise poverty alleviation work more pertinently.</p><p data-animation=\"fadeInLeft\">Once, Wang Yi, an old branch of the village committee, responded to Qin Xining s response that the people s hopes for the mud road to repair the village entrance are all white. In a twinkling of an eye, Gedang Village completed the paving and opening of the oil road from 323 National Highway to 10 kilometers of the village committee's location, hardening the road into a group of 5.3 kilometers.</p>",
            title : "Poverty alleviation. I'm not here to make soy sauce.",
            page :"<span id=\"pagestyle\">01</span>/3",
           },

        lsb : {
            name : "An honest soldier",
            nr : "<p data-animation=\"fadeInLeft\">In January 2016, at the beginning of the New Year, the honest soldier came to Funing County and set foot on this red land for the first time. Poverty touched his heart. The honest soldiers regard it as their important duty and glorious mission to promote Funing County to build a well-off society in an all-round way in synchronization with the whole country.</p><p data-animation=\"fadeInLeft\">In order to fully understand the situation of the county and the people, and to enter the work role as soon as possible, honest soldiers regard visiting and researching as their first job after arriving at their posts. He worked as an English teacher in middle school, joined the army after graduation of master's degree from Peking University, worked as a political teacher for 8 years in the Armored Forces Engineering College of the People's Liberation Army, and transferred to the Procuratorial Daily in October 2007. He is now a researcher of the Party Committee of the Supreme People's Procuratorate. With the experience of different systems and positions, honest soldiers first arrived in Funing and overcame difficulties such as soil and water intolerance and inconvenience in transportation. They ran all over 13 towns and villages in 10 days.</p><p data-animation=\"fadeInLeft\">In Yunnan, Funing is a convenient transportation area, but the eighteen bends of Panshan Road have been sore for several days. Along the way, honest soldiers found that there were five major problems in Funing County, namely, weak infrastructure, limited financial resources at the county level, lagging industrial development, low quality of the poor population, and poverty due to etiological disasters.</p><p data-animation=\"fadeInLeft\">With the support of the leadership of the Supreme People's Procuratorate and after full consideration and deliberation, honest soldiers drafted the Opinions on the Implementation of the Work Plan of the Supreme People's Procuratorate to Fixed Poverty Alleviation and Fortification in Funing County, Yunnan Province, putting forward mechanism and system, precise poverty alleviation, road network reconstruction, port upgrading and port construction, transformation of dangerous houses and relocation of land at one time. Industry development, ecological compensation, e-commerce, beautiful countryside, education and training, cultural poverty alleviation, social assistance, personnel training and other 13 aspects of the direction and measures to help.</p>",
            title : "Be a New Engine for Overcoming Poverty",
            page :"<span id=\"pagestyle\">02</span>/3",
        },

        xdf : {
            name:"Xu Daofeng",
            nr:"<p data-animation=\"fadeInLeft\">The work of poverty alleviation is conscientious work. Since we accept this job, we can not retreat. We must devote ourselves wholeheartedly and do our best. Xu Daofeng, a poverty alleviation cadre of the Chongdu Ditch Management Committee, often said so, and he did the same. Only by going deep into the masses and into the grass-roots level can we grasp the first-hand information. Xu Daofeng learned during his visit that Jia Tai's grandson of poor people suffered from congenital immunodeficiency, but was not included in the poverty alleviation system. Aiming at this problem, both the Poverty Alleviation Office and the comrades stationed in the village team said that children living with their mothers could not be recognized and included.</p><p data-animation=\"fadeInLeft\">Xu Daofeng said, Like Jia Tai, his disabled and old age, the spirit of struggle is the object of our propaganda and learning. His son is paralyzed in bed, his grandson is sick, and the object of our help, we must think of ways. Under Xu Daofeng's multiple communication and coordination, Jia Taisun was eventually incorporated into the system management, so that Jia Tai could enjoy more poverty alleviation policies, and the burden could be lightened accordingly.</p><p data-animation=\"fadeInLeft\">In order to boost the enthusiasm of the masses, Xu Daofeng led the cadres of the three committees of some villages and the poor people to study advanced technology in Xixia and Songxian. After investigation and study, the masses were willing to grow mushrooms, but funds became a problem again. Seeing that the best mushroom planting period will be missed in 2017, he personally resolutely guaranteed a loan of 200,000 yuan for Mowan Village, and lent his credit card to Xinnan Village for use. With the start-up funds, the enthusiasm of the masses increased greatly, and the preparation and seed production of the two villages were in full swing.</p><p data-animation=\"fadeInLeft\">Watching the momentum of the masses come up, he seized the opportunity and helped to win policy funds, so that the two villages developed 250,000 sticks of mushrooms that year, which led to the increase of income of 55 poor households, and also led to the increase of income of more than 130 people around them. Having tasted the sweetness, the planting scale of these two villages has expanded to 350,000 sticks this year, and the people are more confident.</p>",
            title:"Concentrate solely on Poverty Alleviation ",
            page:"<span id=\"pagestyle\">03</span>/3",
        },
         hwx:{
            wenben:"She gave up her job opportunities in big cities and decided to return to Baise, an old revolutionary area, to pursue her dream in her poor hometown, where she had received educational support and left the mountains. <br>She resolutely accepted the task of organizational arrangement, went to remote poverty-stricken villages as the first secretary stationed in the village, regarded poverty alleviation as her long march in the heart, and led 418 poor people from 88 families out of poverty. The incidence of poverty in the whole village dropped by more than 20%.<br> She took pains to say goodbye to her father who had just finished the operation on cancer. She rushed to the affected people in the rain at night. Unfortunately, she was killed by a sudden flash flood on the way.<br>Huang Wenxiu was awarded Excellent Communist Party Member of the Autonomous Region by the Party Committee of Guangxi Zhuang Autonomous Region.",
        },
        lc:{
            wenben:"Luo Tsuo is the representative of the first Secretary of the village in our district and a microcosm of the precise poverty alleviation work. <br> She not only touched every villager in Zhaxigang village, but also is worth learning from every member of the Communist Party. <br>I hope every villager has a carefree life with clothes and food, Luo said. I hope their life will be better and richer, and then I will be more assured.",
        },
        gcy:{
            wenben:"Gong Chen-yu is well aware of the importance of setting an example. He cares about uniting colleagues in his life. He does not push or refuse to let the leader in his work. Both village cadres and team members have great trust in him. <br> He also used all available resources to help villagers solve their living difficulties, help Wachang village group villagers to ask for compensation for accidents, help Jiashan villagers to solve their children's school problems, <br> organize clothing donation activities to help mowa wash away the widowed elderly for winter... Although these seemingly trivial matters, it is this trivial matter that makes Gong Chenyu enter into the hearts of the masses: The poverty alleviation of Dr. Secretary is real.",
        },
    }
}